#if DEBUG
import Foundation

enum DemoAdminFinanceFixtures {
    static let finance = #"""
    {"schemaVersion":"ADMIN_FINANCE_NATIVE_V1","finance":{"currency":"KRW","grossPayments":14850000,"netCollected":13640000,"refundedAndCancelled":1210000,"todayRevenue":174000,"actualCashBalance":10920000,"cumulativePaybackPaid":1860000,"paybackReserve":2320000,"confirmedUnpaidPayback":870000,"pgFeeReserve":612000,"otherUnpaidCosts":450000,"cumulativeConfirmedProfit":5210000,"cumulativeWithdrawals":2400000,"withdrawableAmount":2810000,"pgFeeReserveBps":300,"withdrawalsEnabled":true,"lastReconciledAt":"@T-5m@","recentWithdrawals":[{"id":"withdraw-1","amount":1200000,"status":"COMPLETED","operatorNote":"8월 사업자 계좌 이체","balanceBefore":4010000,"balanceAfter":2810000,"completedAt":"@T-2d@","completedBy":{"id":"admin-1","name":"매쓰 운영자","email":"admin-demo@matths.kr"}},{"id":"withdraw-2","amount":1200000,"status":"COMPLETED","operatorNote":"7월 운영비 출금","balanceBefore":5210000,"balanceAfter":4010000,"completedAt":"@T-32d@","completedBy":{"id":"admin-1","name":"매쓰 운영자","email":"admin-demo@matths.kr"}}]}}
    """#

    static let financeMutation = #"""
    {"schemaVersion":"ADMIN_FINANCE_NATIVE_V1","ok":true,"finance":{"currency":"KRW","grossPayments":14850000,"netCollected":13640000,"refundedAndCancelled":1210000,"todayRevenue":174000,"actualCashBalance":10920000,"cumulativePaybackPaid":1860000,"paybackReserve":2320000,"confirmedUnpaidPayback":870000,"pgFeeReserve":612000,"otherUnpaidCosts":450000,"cumulativeConfirmedProfit":5210000,"cumulativeWithdrawals":2400000,"withdrawableAmount":2810000,"pgFeeReserveBps":300,"withdrawalsEnabled":true,"lastReconciledAt":"@T-0m@","recentWithdrawals":[]}}
    """#

    static let refunds = #"""
    {"schemaVersion":"ADMIN_FINANCE_NATIVE_V1","refunds":{"items":[{"id":"refund-1","user":{"id":"user-1","name":"서지우","email":"demo@matths.kr"},"provider":"APPLE","providerMode":"LIVE","requestedByType":"STUDENT","productCode":"LEARNING_PACKAGE_29","productName":"29일 학습권 패키지","orderReference":"MATTHS-20260901-1423","reasonType":"SIMPLE_CHANGE","reasonDetail":"결제 후 학원 일정이 바뀌어 당분간 서비스를 사용할 수 없습니다.","status":"REQUESTED","requestedAt":"@T-1d@","processingDeadlineAt":"@T+2d@","calculation":{"policyVersion":"","approvedAmount":0,"paidFeatureUsed":false,"usedDays":0,"calculationType":"","calculatedAmount":0,"formula":"","calculatedAt":null,"calculatedBy":null},"decision":{"approvedAmount":0,"cancellationMode":"","providerCancellationTransactionKey":"","providerCancelledAt":null,"processedAt":null,"processedBy":null,"operatorNote":""}},{"id":"refund-2","user":{"id":"user-2","name":"김민준","email":"minjun@example.com"},"provider":"TOSS","providerMode":"LIVE","requestedByType":"PARENT","productCode":"MOCK_EXAM_ONLY","productName":"주간 공식 모의고사 이용권","orderReference":"MATTHS-20260829-8810","reasonType":"SERVICE_FAILURE","reasonDetail":"시험 시작 과정에서 반복 오류가 발생해 응시하지 못했습니다.","status":"CALCULATED","requestedAt":"@T-3d@","processingDeadlineAt":"@T+1d@","calculation":{"policyVersion":"2026-08","approvedAmount":5500,"paidFeatureUsed":false,"usedDays":0,"calculationType":"FULL","calculatedAmount":5500,"formula":"유료 기능 미사용 · 서비스 제공 전 전액 환불","calculatedAt":"@T-2d@","calculatedBy":{"id":"admin-1","name":"매쓰 운영자","email":"admin-demo@matths.kr"}},"decision":{"approvedAmount":0,"cancellationMode":"","providerCancellationTransactionKey":"","providerCancelledAt":null,"processedAt":null,"processedBy":null,"operatorNote":""}}],"filter":{"status":""},"pagination":{"page":1,"total":2,"totalPages":1,"hasPrevious":false,"hasNext":false}}}
    """#

    static let paybacks = #"""
    {"schemaVersion":"ADMIN_FINANCE_NATIVE_V1","paybacks":{"periodKey":"2026-09","eligible":{"total":2,"linkedTotal":1,"payoutRate":50.0,"pendingAmount":29000},"monthly":{"salesAmount":522000,"salesCount":18,"payoutAmount":43500,"payoutCount":3,"payoutToSalesRate":8.3},"rows":[{"cycleId":"cycle-1","userId":"user-1","userName":"서지우","email":"demo@matths.kr","paybackRate":50.0,"paybackAmount":14500,"evaluatedAt":"@T-2d@","payoutDeadlineAt":"@T+5d@","payoutOverdue":false,"accountConfirmed":true,"bankName":"카카오뱅크","accountHolderName":"서지우","accountNumber":"3333-12-3456789","accountNumberLast4":"6789","decryptError":false},{"cycleId":"cycle-2","userId":"user-2","userName":"김민준","email":"minjun@example.com","paybackRate":50.0,"paybackAmount":14500,"evaluatedAt":"@T-10d@","payoutDeadlineAt":null,"payoutOverdue":false,"accountConfirmed":false,"bankName":"","accountHolderName":"","accountNumber":"","accountNumberLast4":"","decryptError":false}],"history":[{"id":"payout-1","user":{"id":"user-3","name":"박하늘","email":"haneul@example.com"},"completedBy":{"id":"admin-1","name":"매쓰 운영자","email":"admin-demo@matths.kr"},"amount":14500,"paybackRate":50.0,"bankName":"신한은행","accountNumberLast4":"9123","status":"COMPLETED","completedAt":"@T-3d@","emailStatus":"FAILED","operatorNote":"송금 거래 0902-001"}],"pagination":{"page":1,"total":2,"totalPages":1,"hasPrevious":false,"hasNext":false}}}
    """#

    static let refundMutation = #"{"schemaVersion":"ADMIN_FINANCE_NATIVE_V1","ok":true,"refunds":{"items":[],"filter":{"status":""},"pagination":{"page":1,"total":0,"totalPages":1,"hasPrevious":false,"hasNext":false}}}"#
    static let mutation = #"{"schemaVersion":"ADMIN_FINANCE_NATIVE_V1","ok":true,"emailDelivered":true}"#
}
#endif
