#if DEBUG
  import Foundation
  enum DemoAdminArenaPolicyFixtures {
    static let dashboard =
      #"{"schemaVersion":"ADMIN_ARENA_POLICY_NATIVE_V1","dashboard":{"matchmaking":{"isPaused":false,"reason":"","pausedAt":null},"learningPackage":{"active":{"id":"lp1","code":"LEARNING-202609","displayName":"29일 학습 패키지","status":"ACTIVE","effectiveFrom":"2026-08-01T00:00:00.000Z","effectiveUntil":null,"priceAmount":29000,"initialLearningDays":29,"initialPaybackScoreDays":29,"maximumTargetTierGap":null,"revengeStakeMultiplier":null,"revengeFeeDays":null,"changeSummary":"출시 가격"},"policies":[]},"mockExam":{"activePrice":5500,"billingPeriodDays":30,"policies":[]},"shop":{"items":[{"code":"PROFILE_RENAME","name":"프로필 이름 변경권","priceDays":2,"enabled":true},{"code":"MATCH_HISTORY_EXPORT","name":"경기 기록 내보내기","priceDays":3,"enabled":true}]},"unranked":{"active":{"id":"sub1","code":"ARENA-SUB-202608","displayName":"Unranked 정식 운영 정책","status":"ACTIVE","effectiveFrom":"2026-08-01T00:00:00.000Z","effectiveUntil":null,"priceAmount":29000,"initialLearningDays":29,"initialPaybackScoreDays":29,"maximumTargetTierGap":null,"revengeStakeMultiplier":null,"revengeFeeDays":null,"changeSummary":"29일 중 15일 공격 출석"},"upcoming":null,"policies":[]},"ranked":{"active":{"id":"main1","code":"MAIN-202608","displayName":"Ranked 정식 운영 정책","status":"ACTIVE","effectiveFrom":"2026-08-01T00:00:00.000Z","effectiveUntil":null,"priceAmount":null,"initialLearningDays":null,"initialPaybackScoreDays":null,"maximumTargetTierGap":3,"revengeStakeMultiplier":2,"revengeFeeDays":1,"changeSummary":"티어 차이별 최소 예치"},"upcoming":null,"policies":[]},"paybackRules":{"cycleDays":29,"minimumAttackParticipationDays":15}}}"#
    static let mutation =
      #"{"schemaVersion":"ADMIN_ARENA_POLICY_NATIVE_V1","ok":true,"dashboard":{"matchmaking":{"isPaused":false,"reason":"","pausedAt":null},"learningPackage":{"active":{"id":"lp1","code":"LEARNING-202609","displayName":"29일 학습 패키지","status":"ACTIVE","effectiveFrom":"2026-08-01T00:00:00.000Z","effectiveUntil":null,"priceAmount":29000,"initialLearningDays":29,"initialPaybackScoreDays":29,"maximumTargetTierGap":null,"revengeStakeMultiplier":null,"revengeFeeDays":null,"changeSummary":"출시 가격"},"policies":[]},"mockExam":{"activePrice":5500,"billingPeriodDays":30,"policies":[]},"shop":{"items":[{"code":"PROFILE_RENAME","name":"프로필 이름 변경권","priceDays":2,"enabled":true}]},"unranked":{"active":null,"upcoming":null,"policies":[]},"ranked":{"active":null,"upcoming":null,"policies":[]},"paybackRules":{"cycleDays":29,"minimumAttackParticipationDays":15}}}"#
  }
#endif
