#if DEBUG
import Foundation

enum DemoAdminCommunityFixtures {
    private static let body = #"""
    {"posts":[{"id":"post-1","boardType":"high-school","schoolCode":"","schoolName":"","title":"시험 직전 문제 공유합니다","content":"개인정보 없이 풀이 방법과 문제 접근 순서만 공유합니다.","status":"published","isPinned":false,"warningIssued":false,"moderationReason":"","viewCount":84,"createdAt":"@T-3h@","author":{"id":"user-2","name":"김민준","email":"minjun@example.com","role":"student","warningCount":1}},{"id":"post-2","boardType":"retaker","schoolCode":"","schoolName":"","title":"운영 정책 위반으로 숨긴 글","content":"관리자가 신고를 검토해 숨긴 게시글의 내용입니다.","status":"hidden","isPinned":false,"warningIssued":true,"moderationReason":"개인정보 노출 및 반복 홍보","viewCount":21,"createdAt":"@T-2d@","author":{"id":"user-3","name":"이하늘","email":"haneul@example.com","role":"student","warningCount":2}}],"notices":[{"id":"notice-1","boardType":"high-school","schoolCode":"","schoolName":"","universityCode":"","universityName":"","title":"게시판 이용 안내","content":"개인정보와 정답 유출 없이 서로 도움이 되는 학습 정보를 나눠주세요.","status":"published","isPinned":true,"isSystem":true,"createdAt":"@T-20d@","updatedAt":"@T-1d@"}],"comments":[{"id":"comment-1","postId":"post-1","postTitle":"시험 직전 문제 공유합니다","content":"연락처를 올리면 안 됩니다. 본문에서 지워주세요.","status":"published","warningIssued":false,"moderationReason":"","createdAt":"@T-1h@","author":{"id":"user-4","name":"박지안","email":"jian@example.com","role":"student","warningCount":0}}],"reports":[{"id":"report-1","status":"pending","reason":"본문에 외부 연락처와 반복 홍보 문구가 있습니다.","resolution":"","createdAt":"@T-40m@","reporter":{"id":"user-5","name":"신고 학생","email":"reporter@example.com","role":"student","warningCount":0},"reportedUser":{"id":"user-3","name":"이하늘","email":"haneul@example.com","role":"student","warningCount":2},"post":{"id":"post-2","boardType":"retaker","schoolCode":"","schoolName":"","title":"운영 정책 위반으로 숨긴 글","content":"관리자가 신고를 검토해 숨긴 게시글의 내용입니다.","status":"hidden","isPinned":false,"warningIssued":true,"moderationReason":"개인정보 노출 및 반복 홍보","viewCount":21,"createdAt":"@T-2d@","author":{"id":"user-3","name":"이하늘","email":"haneul@example.com","role":"student","warningCount":2}}}],"boardLabels":{"high-school":"통합 게시판","school":"학교 게시판","retaker":"N수생 게시판","university":"대학교 게시판","worker":"직장인 게시판"},"filters":{"board":"","status":"","search":""},"stats":{"total":2,"published":1,"hidden":1,"deleted":0},"pagination":{"page":1,"totalPages":1,"total":2,"hasPrevious":false,"hasNext":false}}
    """#
    static var dashboard: String { #"{"schemaVersion":"ADMIN_COMMUNITY_NATIVE_V1","community":\#(body)}"# }
    static var mutation: String { #"{"schemaVersion":"ADMIN_COMMUNITY_NATIVE_V1","ok":true,"result":null,"community":\#(body)}"# }
}
#endif
